#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export PATH="$PATH:/usr/local/bin/npm_modules"
export PATH="$PATH:/Users/burkel/chromedriver"
alias ll='ls -lGa'
alias pip-clear='pip freeze | xargs pip uninstall -y'

# set -o vi
export VISUAL=vi
export EDITOR=$VISUAL
